"""CADCodeVerify (Alrashedy et al., ICLR 2025) re-implemented as a baseline.

The authors released only the CADPrompt data, so this follows the paper (Sec. 3.3,
Appendix Figures 11-14): generate 2-5 yes/no verification questions from the
description; answer them from 4 rendered views of the generated part (Yes / No /
Unclear, with reasoning); turn the non-"Yes" answers into feedback; rewrite the code.
Two refinement rounds, as in the paper. The same LLM as every other method is used
(the paper used GPT-4 / Gemini / CodeLlama). Prompts are the paper's, verbatim.
"""

from __future__ import annotations

import re
import threading
import time
from pathlib import Path
from typing import Optional

from . import roles
from .llm import Usage, image_block
from .pipeline import Budget, Engine, MethodResult, RSTConfig, _charge

_RENDER_LOCK = threading.Lock()   # VTK off-screen rendering is not thread-safe

QUESTION_PROMPT = """You will be given a description of how a human-designer would describe the design of a 3D object. Your job is to provide between 2-5 (Yes or No) questions that I can use to verify how similar the generated object is to the description generated by a human. The questions should be framed such that answering "No" implies that there is a change that needs to be made to the object regarding the verification question.
Here are some important points to note for this task;
(1) Do not make up questions if you cannot generate 5 questions based on the description provided.
(2) Ensure that your questions only reference entities mentioned within the description.
(3) Try not to reference orientation the components of the 3D object. Your generated questions should not ask whether a component is on the "right" or "left" side as this orientation is relative.
I will give you two examples with a language description followed by the appropriate verification questions. Please reference these examples while generating your verification questions.
### Example 1 ###
Description:
Extrude a cylindrical plate with a rectangular hole in the middle of it.
Generated Questions:
1. Is the object cylindrical in shape?
2. Does the object have a rectangular hole in the center?
3. Is the object extruded in one dimension?
### Example 2 ###
Description:
Design a 3D object that resembles a cone. First draw a sketch of a square and extrude it to create the base of the cone. Next, draw a sketch of a circle centered at the center of the square base. Extrude this sketch vertically into a conical shape, such that the diameter of the circle decreases as the height increases. Finally cutout the tip of the cone, such that the tip of the cone is now rectangular in shape.
Generated Questions:
1- Does the object resemble a cone?
2- Is the base of the object square-shaped?
3- Is the circular base of the cone centered at the same point as the center of the square base?
4- Is the tip of the cone rectangular?
5- Does the diameter of the cone decrease as the height increases?"""

ANSWER_PROMPT = """Your job is to answer this set of questions with respect to the object I have shared with you. I will be providing 4 images of the object from different orientations so that you can get a complete picture of the 3D object. Here are some important points to note regarding your task:
(1) Remember that these images are all of the same object from different angles.
(2) The answer to each of these questions should always be one of three options which are "Yes" or "No" or "Unclear."
(3) Your answer should be "Unclear" in situations where you are unsure of the answer or do not have enough information to answer the question.
Make sure to provide reasoning supporting all your answers.
# Your answer should follow the same format as below:
1. **Question?**
- **Answer:**
- **Reasoning:**
2. **Question?**
- **Answer:**
- **Reasoning:**"""

FEEDBACK_PROMPT = """These were the answers to the questions I asked to validate a generated 3D object. Can you utilize the answers to these questions to generate actionable feedback that will help the model to correct the mistakes in the 3D object? Your job is to summarize these answers into practical corrections that need to be made to the 3D object. Please note the following while generating your feedback:
(1) The corrections should be such that the answers to all questions provided will become yes upon applying the suggested corrections.
(2) Your corrections should not change the object such that any of the answers that are already, "Yes" become "No."
(3) You only want to change the object such that the answers which are "No" or "Unclear" become "Yes." The summary should be specific and only a few sentences long.
(4) Your corrections should not be regarding the quality or orientation of the images.
(5) Your feedback should not attempt to fix issues in the scale. DO NOT ask for the addition of additional scale or reference objects.
(6) Do not ask for details regarding the size or dimensions of the object.
(7) Your corrections should be constructed such that a human designer can use your feedback to update the 3D object such that all questions have "Yes" as the answer."""

REFINE_SYSTEM = """You improve a CadQuery program using feedback from a visual inspection of the 3D object it produces.
Assign the final shape to `result`. Output ONLY the corrected, complete Python code, no fences, no explanation."""

VIEWS = [(30, 45), (30, 225), (85, 0), (5, 0)]  # (elevation, azimuth): two isometrics, top, front


def render_four_views(stl_path: str, png_path: str) -> str:
    """2x2 composite of four views (the paper gives the VLM 4 images of the object)."""
    import numpy as np
    import vtk
    with _RENDER_LOCK:
        reader = vtk.vtkSTLReader()
        reader.SetFileName(stl_path)
        reader.Update()
        normals = vtk.vtkPolyDataNormals()
        normals.SetInputConnection(reader.GetOutputPort())
        normals.SetFeatureAngle(30.0)
        normals.SplittingOn()
        normals.Update()
        b = normals.GetOutput().GetBounds()
        center = [(b[0] + b[1]) / 2, (b[2] + b[3]) / 2, (b[4] + b[5]) / 2]
        extent = max(b[1] - b[0], b[3] - b[2], b[5] - b[4], 1e-6)
        win = vtk.vtkRenderWindow()
        win.SetOffScreenRendering(1)
        win.SetSize(1400, 1400)
        for k, (elev, azim) in enumerate(VIEWS):
            mapper = vtk.vtkPolyDataMapper()
            mapper.SetInputConnection(normals.GetOutputPort())
            actor = vtk.vtkActor()
            actor.SetMapper(mapper)
            actor.GetProperty().SetColor(0.45, 0.68, 0.95)
            actor.GetProperty().SetInterpolationToPhong()
            ren = vtk.vtkRenderer()
            ren.AddActor(actor)
            ren.SetBackground(1, 1, 1)
            x0, y0 = (k % 2) / 2, 0.5 - (k // 2) / 2
            ren.SetViewport(x0, y0, x0 + 0.5, y0 + 0.5)
            e, a = np.radians(elev), np.radians(azim)
            d = extent * 2.5
            cam = ren.GetActiveCamera()
            cam.SetPosition(center[0] + d * np.cos(e) * np.cos(a), center[1] + d * np.cos(e) * np.sin(a),
                            center[2] + d * np.sin(e))
            cam.SetFocalPoint(*center)
            cam.SetViewUp(0, 1, 0) if elev > 80 else cam.SetViewUp(0, 0, 1)
            ren.ResetCamera()
            cam.Zoom(0.9)
            win.AddRenderer(ren)
        win.Render()
        w2i = vtk.vtkWindowToImageFilter()
        w2i.SetInput(win)
        w2i.Update()
        writer = vtk.vtkPNGWriter()
        writer.SetFileName(png_path)
        writer.SetInputConnection(w2i.GetOutputPort())
        writer.Write()
        win.Finalize()
    return png_path


def _questions(text: str) -> list[str]:
    qs = []
    for line in text.splitlines():
        m = re.match(r"\s*\d+\s*[\.\-\)]\s*(.+\?)\s*$", line)
        if m:
            qs.append(m.group(1).strip())
    return qs[:5]


def _answers(text: str, n: int) -> list[str]:
    ans = re.findall(r"Answer:\**\s*\**\s*(Yes|No|Unclear)", text, flags=re.I)
    ans = [a.capitalize() for a in ans][:n]
    return ans + ["Unclear"] * (n - len(ans))


def run_cadcodeverify(eng: Engine, p0: str, cfg: RSTConfig, pre=None, rounds_max: int = 2) -> MethodResult:
    t0 = time.time()
    usage = eng.llm.usage = Usage()
    _charge(usage, pre)
    budget = Budget(usage, cfg.max_llm_calls)
    log: list = []
    res, code = eng.execute(p0, [], budget, cfg.max_error_fixes, log)
    qtext = eng.llm.complete(QUESTION_PROMPT, f"Description:\n{eng.prompt}\nGenerated Questions:", role="ccv_questions",
                             temperature=0.0)
    questions = _questions(qtext)
    stopped = "rounds"
    for k in range(rounds_max):
        if not res.success or not res.stl_path or not questions or not budget.ok(3):
            stopped = "exec_failed" if not res.success else "budget"
            break
        png = str(Path(res.stl_path).with_suffix(".views.png"))
        try:
            render_four_views(res.stl_path, png)
        except Exception as e:
            log.append({"step": "render_failed", "error": str(e)[:200]})
            stopped = "render_failed"
            break
        qlist = "\n".join(f"{i + 1}. {q}" for i, q in enumerate(questions))
        atext = eng.llm.complete_blocks(ANSWER_PROMPT, [image_block(png), {"type": "text", "text": qlist}],
                                        role="ccv_answer", temperature=0.0)
        answers = _answers(atext, len(questions))
        entry = {"step": "verify", "round": k + 1, "questions": questions, "answers": answers}
        if all(a == "Yes" for a in answers):
            entry["decision"] = "all_yes"
            log.append(entry)
            stopped = "all_yes"
            break
        qa = "\n".join(f"{i + 1}. {q}\nAnswer: {a}" for i, (q, a) in enumerate(zip(questions, answers)) if a != "Yes")
        feedback = eng.llm.complete(FEEDBACK_PROMPT, qa, role="ccv_feedback", temperature=0.0)
        new = roles.strip_fences(eng.llm.complete(
            REFINE_SYSTEM, f"DESCRIPTION:\n{eng.prompt}\n\nCURRENT CODE:\n```python\n{code}\n```\n\nFEEDBACK:\n{feedback}\n",
            role="ccv_refine"))
        new_res, new_code = eng.execute(new, [], budget, cfg.max_error_fixes, log)
        entry.update({"feedback": feedback[:1000], "code": new_code, "success": new_res.success})
        log.append(entry)
        if new_res.success:
            res, code = new_res, new_code
    return MethodResult("cadcodeverify", code, res.to_dict() if res is not None else None, log, usage.to_dict(),
                        eng.kernel.calls, time.time() - t0, [], [], stopped)
